APPLICATION=test_net_netif

#BOARD = samr21-xpro
BOARD = native

RIOTBASE ?= $(CURDIR)/../../../RIOT

USEMODULE += netif

# Change this this to see if macros can be configures using CFLAGS
# Use make menuconfig command alternatively to access GUI.

# CFLAGS += -DCONFIG_NETIF_NAMELENMAX=6

include $(RIOTBASE)/Makefile.include
