APPLICATION=test_net_asymcute

#BOARD = samr21-xpro
BOARD = native

RIOTBASE ?= $(CURDIR)/../../../RIOT


USEMODULE += credman

# Chage this this to see if macros can be configures using CFLAGS
# Use make menuconfig command alternatively to access GUI.

# CFLAGS += -DCONFIG_CREDMAN_MAX_CREDENTIALS=3

include $(RIOTBASE)/Makefile.include
